package com.davealone69.githubboss.data

/**
 * Offline complete-app guide generator.
 * Produces architecture, build steps, file plan, and Termux-friendly tips
 * so the LLM path can act as a full app coach — not only single-screen code.
 */
object AppGuideGenerator {

    fun generateGuide(
        prompt: String,
        includeRoom: Boolean,
        includeHilt: Boolean,
        includeWorkflows: Boolean,
        packageName: String = "com.example"
    ): GeneratedFile {
        val clean = prompt.trim().ifBlank { "Android app" }
        val slug = clean.lowercase()
            .replace(Regex("[^a-z0-9]+"), "-")
            .trim('-')
            .take(24)
            .ifBlank { "my-app" }

        val features = buildList {
            add("Jetpack Compose + Material 3 UI")
            add("ViewModel + StateFlow")
            if (includeRoom) add("Room local database")
            if (includeHilt) add("Hilt dependency injection")
            if (includeWorkflows) add("GitHub Actions CI (build APK)")
            add("Phone-first layouts")
        }

        val content = """
# Complete App Guide: $clean

Generated by **GitHub-Boss-Pro** (free offline guide).
Use this as your build checklist on phone + Termux.

---

## 1. Goal

Build: **$clean**

Package: `$packageName`
Suggested app id: `$packageName.${slug.replace("-", "")}`

---

## 2. Architecture (simple & solid)

```
app/
  ui/          # Screens + ViewModels + UiState
  data/        # Repository, API, Room (if needed)
  MainActivity.kt
```

- **UI** talks only to ViewModels
- **ViewModels** talk to Repository
- **Repository** owns network / DB
- Prefer one screen = one ViewModel + one UiState

---

## 3. Features planned

${features.joinToString("\n") { "- $it" }}

---

## 4. Step-by-step build order

1. **Create project** (Android Studio or copy skeleton from GitHub-Boss-Pro)
2. **Set package** to `$packageName`
3. **Add dependencies** (Compose, Lifecycle${if (includeRoom) ", Room" else ""}${if (includeHilt) ", Hilt" else ""})
4. **MainActivity** + theme + navigation (start with one screen)
5. **UiState + ViewModel** for the main flow
6. **Compose Screen** wired to ViewModel
${if (includeRoom) "7. **Room entity + DAO + DB** then repository\n8. **Wire repository into ViewModel**\n" else "7. **Repository** (even if stub data at first)\n"}9. **Error / loading / empty states**
10. **Test on phone** (`./gradlew assembleDebug`)
${if (includeWorkflows) "11. **Push + CI** — confirm GitHub Actions builds APK\n" else ""}

---

## 5. Termux / phone tips

```bash
# Build debug APK
./gradlew assembleDebug

# Install on device (USB or wireless adb)
adb install -r app/build/outputs/apk/debug/app-debug.apk

# Logcat while testing
adb logcat | grep -i "${slug.take(12)}"
```

- Keep PAT and Gemini keys **out of git**
- Use GitHub-Boss-Pro Builder to regenerate screens as you iterate
- Commit small: one screen or one data layer at a time

---

## 6. File checklist

| Path | Purpose |
|------|---------|
| `MainActivity.kt` | Entry + setContent |
| `ui/*Screen.kt` | Compose UI |
| `ui/*ViewModel.kt` | State + actions |
| `ui/*UiState.kt` | Immutable UI state |
| `data/*Repository.kt` | Business/data access |
${if (includeRoom) "| `data/*Entity.kt` / DAO | Local storage |\n" else ""}${if (includeWorkflows) "| `.github/workflows/*.yml` | CI build |\n" else ""}

---

## 7. Next prompts to try in Builder

- "$clean main screen with list"
- "$clean detail screen"
- "$clean settings screen"
${if (includeRoom) "- \"$clean Room entity and DAO\"\n" else ""}- "Add error and empty states to $clean"

---

## 8. Definition of done

- [ ] App installs on phone
- [ ] Main flow works offline (or with clear offline message)
- [ ] No secrets in repo
- [ ] Debug APK builds in CI (if enabled)
- [ ] You can explain the architecture in one minute

---

*Guide is deterministic and free. Turn on Gemini in Builder for a smarter custom plan.*
        """.trimIndent()

        return GeneratedFile(
            path = "docs/APP_GUIDE.md",
            category = "Docs",
            content = content
        )
    }

    /** Gemini system prompt when user wants a complete app guide + code. */
    fun geminiGuideSystemPrompt(packageName: String): String = """
You are an expert Android app coach and Kotlin engineer.
The user wants a COMPLETE APP GUIDE plus production-ready starter code.

Package: $packageName

You MUST output:

1) A guide file first:
### FILE: docs/APP_GUIDE.md
```markdown
(full guide: goal, architecture diagram in text, step-by-step build order,
Termux/phone tips, file checklist, definition of done)
```

2) Then Kotlin/Compose files in the same format:
### FILE: path/to/FileName.kt
```kotlin
// full file content
```

Rules:
- Material 3, StateFlow, viewModelScope, collectAsStateWithLifecycle
- Include MainActivity stub, at least one Screen + ViewModel + UiState
- Keep code phone-friendly and copy-paste ready
- No secrets; no explanations outside FILE blocks
    """.trimIndent()
}
