package com.davealone69.githubboss.data

data class GeneratedFile(
    val path: String,
    val category: String, // "Android", "Workflow", "Docs", "Config", "Kotlin"
    val content: String
)

fun generateProjectFiles(
    prompt: String,
    includeRoom: Boolean,
    includeHilt: Boolean,
    includeWorkflows: Boolean,
    includeGemini: Boolean,
    minSdk: String,
    packageName: String = "com.example"
): List<GeneratedFile> {
    val list = mutableListOf<GeneratedFile>()

    val kotlinFiles = KotlinCodeMaker.generate(
        prompt = prompt,
        packageName = packageName
    )
    kotlinFiles.forEach { kf ->
        list += GeneratedFile(
            path = "app/src/main/java/${packageName.replace('.', '/')}/${kf.path}",
            category = if (kf.name.endsWith(".md")) "Docs" else "Kotlin",
            content = kf.content
        )
    }

    val appSlug = prompt.lowercase().replace(Regex("[^a-z0-9]"), "").take(12).ifEmpty { "myapp" }

    list += GeneratedFile(
        path = "app/build.gradle.kts",
        category = "Android",
        content = """
plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace = "$packageName"
    compileSdk = 35

    defaultConfig {
        applicationId = "$packageName.$appSlug"
        minSdk = $minSdk
        targetSdk = 35
        versionCode = 1
        versionName = "1.0.0"
    }

    buildFeatures {
        compose = true
    }
}

dependencies {
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    ${if (includeRoom) "implementation(\"androidx.room:room-runtime:2.6.1\")\n    implementation(\"androidx.room:room-ktx:2.6.1\")" else ""}
}
        """.trimIndent()
    )

    list += GeneratedFile(
        path = "app/src/main/AndroidManifest.xml",
        category = "Android",
        content = """
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/Theme.MyApplication">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
        """.trimIndent()
    )

    if (includeWorkflows) {
        list += GeneratedFile(
            path = ".github/workflows/build-android.yml",
            category = "Workflow",
            content = """
name: Build & Test Android
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew || true
      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
            """.trimIndent()
        )
    }

    list += GeneratedFile(
        path = "README.md",
        category = "Docs",
        content = """
# $prompt

Generated by **GitHub-Boss-Pro** Kotlin Code Maker.

## Features
- Jetpack Compose + Material 3
- ViewModel + StateFlow
${if (includeRoom) "- Room database stubs" else ""}
${if (includeWorkflows) "- GitHub Actions CI" else ""}

## Build
```bash
./gradlew assembleDebug
```
        """.trimIndent()
    )

    return list
}
