package com.davealone69.githubboss.data

/**
 * Builds useful Termux command snippets from a short description.
 * Offline and deterministic; optional Gemini can refine later.
 */
object TermuxCommandGenerator {

    fun generate(description: String): List<HelpCoach.TermuxSnippet> {
        val d = description.trim().lowercase()
        if (d.isBlank()) return defaultSet()

        val out = mutableListOf<HelpCoach.TermuxSnippet>()

        if (d.contains("clone") || d.contains("git")) {
            out += HelpCoach.TermuxSnippet("Clone repo", "git clone https://github.com/OWNER/REPO.git")
            out += HelpCoach.TermuxSnippet("Clone with SSH", "git clone git@github.com:OWNER/REPO.git")
            out += HelpCoach.TermuxSnippet("Status", "git status")
            out += HelpCoach.TermuxSnippet("Pull", "git pull")
        }
        if (d.contains("build") || d.contains("gradle") || d.contains("apk")) {
            out += HelpCoach.TermuxSnippet("Build debug APK", "./gradlew assembleDebug")
            out += HelpCoach.TermuxSnippet("Build release AAB", "./gradlew bundleRelease")
            out += HelpCoach.TermuxSnippet("Clean build", "./gradlew clean assembleDebug")
        }
        if (d.contains("install") || d.contains("adb") || d.contains("device")) {
            out += HelpCoach.TermuxSnippet("List devices", "adb devices")
            out += HelpCoach.TermuxSnippet("Install debug APK", "adb install -r app/build/outputs/apk/debug/*.apk")
            out += HelpCoach.TermuxSnippet("Uninstall package", "adb uninstall com.example.app")
            out += HelpCoach.TermuxSnippet("Logcat", "adb logcat -v time")
        }
        if (d.contains("ssh") || d.contains("key")) {
            out += HelpCoach.TermuxSnippet("Generate SSH key", "ssh-keygen -t ed25519 -C \"phone@termux\"")
            out += HelpCoach.TermuxSnippet("Show public key", "cat ~/.ssh/id_ed25519.pub")
            out += HelpCoach.TermuxSnippet("Start ssh-agent", "eval \$(ssh-agent -s) && ssh-add ~/.ssh/id_ed25519")
        }
        if (d.contains("python") || d.contains("pip")) {
            out += HelpCoach.TermuxSnippet("Update packages", "pkg update && pkg upgrade -y")
            out += HelpCoach.TermuxSnippet("Install Python", "pkg install python -y")
            out += HelpCoach.TermuxSnippet("Pip install", "pip install -r requirements.txt")
        }
        if (d.contains("node") || d.contains("npm")) {
            out += HelpCoach.TermuxSnippet("Install Node", "pkg install nodejs -y")
            out += HelpCoach.TermuxSnippet("NPM install", "npm install")
        }
        if (d.contains("open") || d.contains("url") || d.contains("browser")) {
            out += HelpCoach.TermuxSnippet("Open URL", "termux-open-url https://github.com")
        }

        if (out.isEmpty()) out += defaultSet()
        return out.distinctBy { it.command }
    }

    fun toShellFile(snippets: List<HelpCoach.TermuxSnippet>): String {
        return buildString {
            appendLine("# Termux commands — generated by GitHub-Boss-Pro")
            appendLine("# Copy line-by-line or source this file")
            appendLine()
            snippets.forEach { s ->
                appendLine("# ${s.label}")
                appendLine(s.command)
                appendLine()
            }
        }
    }

    private fun defaultSet() = listOf(
        HelpCoach.TermuxSnippet("Update packages", "pkg update && pkg upgrade -y"),
        HelpCoach.TermuxSnippet("Git status", "git status"),
        HelpCoach.TermuxSnippet("Build debug APK", "./gradlew assembleDebug"),
        HelpCoach.TermuxSnippet("Install APK", "adb install -r app/build/outputs/apk/debug/*.apk"),
        HelpCoach.TermuxSnippet("Open GitHub", "termux-open-url https://github.com")
    )
}
